FROM node:lts-alpine AS production

ENV NODE_ENV production

# Add the work directory
WORKDIR /app

# Cache and install dep
COPY package.json .
COPY yarn.lock .
RUN npm install --production

# Copy app files
COPY . .
# Build the app
RUN npm run build

# Bundle static assets with nginx
FROM nginx:alpine as production
ENV NODE_ENV production
# Copy built assets from builder
COPY --from=builder /app/build /usr/share/nginx/html
# Add your nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Expose port
EXPOSE 80
# Start nginx
CMD ["nginx", "-g", "daemon off;"]